# Generated by Django 2.2.5 on 2019-09-15 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='name')),
                ('user_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('authority', models.IntegerField(default=0, verbose_name='authority')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
                ('user_user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
