# Generated by Django 2.2.5 on 2019-09-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user_contact',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user_cpi',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user_reg_no',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='year',
        ),
    ]
