# Generated by Django 2.2.5 on 2019-09-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='type',
        ),
        migrations.AddField(
            model_name='user_details',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='discription'),
        ),
    ]
