# Generated by Django 2.2.5 on 2019-09-15 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='videoOrg',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('id2', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('isPrivate', models.BooleanField(default=False)),
                ('report', models.IntegerField(default=0)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videoOrg')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='video.tag')),
            ],
        ),
    ]
