# Generated by Django 2.2.5 on 2019-09-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoorg',
            name='name',
        ),
    ]
