# Generated by Django 2.2.5 on 2019-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190913_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
