# Generated by Django 2.2.5 on 2019-09-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_auto_20190915_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=200)),
                ('c2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('report', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vidid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
        ),
    ]
