# Generated by Django 2.2.5 on 2019-09-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20190913_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoOrg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videoOrg'),
        ),
    ]
