# Generated by Django 2.2.5 on 2019-09-18 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_comment_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='c1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentcomment', to='video.comment'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='c2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childcomment', to='video.comment'),
        ),
    ]
